; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp_lora_receiver

[env]
platform = espressif32@6.5.0
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D HELTEC_BOARD=30
    -D SLOW_CLK_TPYE=0
    -D LoRaWAN_DEBUG_LEVEL=0
    -D WIFI_LORA_32_V3=1
    -D RADIO_CHIP_SX1262=1
    -D ACTIVE_REGION=LORAMAC_REGION_US915
    -D REGION_US915=1
    -D LORA_DISPLAY=0
    -D GPIO_PIN_COUNT=48

lib_ldf_mode = deep

lib_deps =
    madhephaestus/ESP32Servo
    bblanchon/ArduinoJson @ ^7.0.4
    WiFi
    WebServer
    HTTPClient
    heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5

[env:esp_lora_transmitter]
build_src_filter = +<transmitter/>
build_flags = ${env.build_flags} -I include/transmitter

[env:esp_lora_receiver]
build_src_filter = +<receiver/>
build_flags = ${env.build_flags} -I include/receiver

[env:esp_display]
build_src_filter = +<display/>
build_flags = ${env.build_flags} -I include/display


